### ISSUE TITLE
can't render with color

### ISSUE THREAD

**Issue by plusect** [KonghaYao/docsify-drawio#3]
the style of rounded rectangle is 
`rounded=1;whiteSpace=wrap;html=1;fillColor=#dae8fc;strokeColor=#6c8ebf;gradientColor=#7ea6e0;`

The error msg:
```
viewer.min.js:3953 
      
       SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.GraphViewer.createViewerForElement (viewer.min.js:3955:110)
    at viewer.min.js:3953:149
    at Object.forEach (viewer.min.js:235:512)
    at Function.GraphViewer.processElements (viewer.min.js:3953:49)
    at drawio.js:45:36
    at a (docsify.min.js:1:21660)
    at V (docsify.min.js:1:21698)
    at r (docsify.min.js:1:104699)
    at docsify.min.js:1:104769
```

**Comment by rodravknight** [comment]
I have exactly the same issue, is something I'm doing wrong?
